DROP TABLE HCG_TERMS_AND_CONDITIONS;

CREATE TABLE HCG_TERMS_AND_CONDITIONS (
    AWARD_ID                                 VARCHAR2(55),
    TERMS_AND_CONDITIONS_ID                  VARCHAR2(22),
    TERMS_AND_CONDITIONS_NAME                VARCHAR2(67),
    SPECIAL_TERMS_AND_CONDITIONS_ID          VARCHAR2(22),
    SPECIAL_TERMS_AND_CONDITIONS_NAME        VARCHAR2(316)
);
