DROP TABLE HCG_AWARD_WORKSPACE;

CREATE TABLE hcg_award_workspace
(
  award_id                                VARCHAR2(500),
  awd_name                                VARCHAR2(500),
  current_state                           VARCHAR2(500),
  pi_pd_id                                VARCHAR2(500),
  pi_pd_name                              VARCHAR2(500),
  business_unit_name                      VARCHAR2(500),
  business_unit_id                        VARCHAR2(500),
  research_center_id                     VARCHAR2(500),
  research_center_name                   VARCHAR2(500),
  clinical_division_id                   VARCHAR2(500),
  clinical_division_name                 VARCHAR2(500),
  grants_and_contracts_specialist_id     VARCHAR2(500),
  grants_and_contracts_specialist_name   VARCHAR2(500),
  grants_and_finance_administrator_id    VARCHAR2(500),
  grants_and_finance_administrator_name  VARCHAR2(500),
  grants_accountant_id                   VARCHAR2(500),
  grants_accountant_name                 VARCHAR2(500),
  award_number                           VARCHAR2(500),
  protocol_number                        VARCHAR2(500),
  current_pop_start_date                 DATE,
  current_pop_end_date                   DATE,
  start_date                             DATE,
  end_date                               DATE,
  award_structure                        VARCHAR2(500),
  sponsor_id                             VARCHAR2(500),
  sponsor_name                           VARCHAR2(500),
  sponsor_contact_info_name              VARCHAR2(500),
  sponsor_contact_info_email             VARCHAR2(500),
  sponsor_award_id                       VARCHAR2(500),
  fund_code                              VARCHAR2(500),
  fund_code_name                         VARCHAR2(500),
  previous_award_number                 VARCHAR2(500),
  psft_award_id                          VARCHAR2(500),
  psft_project_id                        VARCHAR2(500),
  health_plan                            VARCHAR2(500),
  awarded_funding_proposal_id           VARCHAR2(500),
  parent_award_id                        VARCHAR2(500),
  is_child                               VARCHAR2(500),
  is_parent                              VARCHAR2(500)
);