DROP TABLE HCG_HUMAN_SUBJECTS_RESEARCH;

CREATE TABLE HCG_HUMAN_SUBJECTS_RESEARCH (
    AWARD_ID                       VARCHAR2(100),

    IRB_STATUS                     VARCHAR2(50),

    IRB_APPROVAL_DATE              DATE,

    IRB_PROTOCOL_NUMBER            VARCHAR2(250),

    IRB_ADDITIONAL_INFORMATION     VARCHAR2(500)
);